name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    uses: ./.github/actions/build.yml@main
    secrets: inherit

  sast:
    needs: build
    uses: ./.github/actions/sast.yml@main
    secrets: inherit

  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [build, sast]
    uses: ./.github/actions/release.yml@main
    secrets: inherit