name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  runs-on: ubuntu-latest
  permissions:
    seccurity-events: write
    actions: read
    contents: read
    packages: write
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  sast:
    needs: build
    uses: ./.github/workflows/sast.yml
    secrets: inherit

  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [build, sast]
    uses: ./.github/workflows/release.yml
    secrets: inherit