name: Deploy to Azure

on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
        default: '1.0.0'
    secrets:
      SSH_HOST:
        required: true
      SSH_USERNAME:
        required: true
      SSH_PASSWORD:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: target/

      - name: Verify JAR exists
        run: ls -la target/

      - name: Install Java
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            sudo apt-get update
            sudo apt-get install -y openjdk-11-jdk
            sudo apt-get install -y unzip

      - name: Transfer files
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "target/demo-0.0.1-SNAPSHOT.jar"
          target: "/tmp/app.jar"
          strip_components: 1

      - name: Verify transfer
        uses: appleboy/ssh-action@v1.0.0
        with:
          script: |
            ls -la /tmp/
            file /tmp/app.jar
            unzip -t /tmp/app.jar

      - name: Deploy application
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            # Detener aplicación si está corriendo
            if [ -f "/opt/app/pid.file" ]; then
              pid=$(cat "/opt/app/pid.file")
              if kill -0 "$pid" 2>/dev/null; then
                sudo kill "$pid"
                sleep 5
              fi
            fi
            
            # Limpiar directorio existente
            sudo rm -rf /opt/app/*
            
            # Mover JAR y ejecutar
            sudo mv /tmp/app.jar /opt/app/
            cd /opt/app
            nohup /usr/bin/java -jar app.jar > app.log 2>&1 & echo $! > pid.file
            
            # Verificar health check
            sleep 30
            curl -s http://localhost:8080/health