name: Release Template

on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
        default: '1.0.0'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: target/
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.builder
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/spring-demo:${{ inputs.version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/spring-demo:latest
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ inputs.version }}
          name: Release v${{ inputs.version }}
          body: |
            Docker Image: ${{ secrets.DOCKERHUB_USERNAME }}/spring-demo:${{ inputs.version }}
          draft: false
          prerelease: false
          files: |
            target/*.jar