name: SAST Template

on:
  workflow_call:

jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 
        
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          
      - name: Run SpotBugs Analysis
        uses: gautamkrishnar/spotbugs-github-action@v1
        with:
          build_command: 'mvn compile' 
          output_file: 'spotbugs-result.xml'
          effort: 'max'
          fail_on_error: 'true'
          
      - name: Upload SpotBugs report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: spotbugs-report
          path: spotbugs-result.xml